# Generated by Django 5.2.7 on 2026-02-16 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple_farm', 'Яблочная ферма'), ('banana_plantation', 'Банановая плантация'), ('orange_grove', 'Апельсиновая роща'), ('grape_vineyard', 'Виноградник'), ('strawberry_field', 'Клубничное поле')], max_length=50, unique=True, verbose_name='Тип здания')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True, verbose_name='ID игрока')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('carrot', 'Морковь'), ('potato', 'Картофель'), ('tomato', 'Помидор'), ('cucumber', 'Огурец'), ('cabbage', 'Капуста')], max_length=50, unique=True, verbose_name='Тип ресурса')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('building', 'Покупка здания'), ('resource', 'Покупка ресурса')], max_length=20, verbose_name='Тип сделки')),
                ('resource_quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма сделки')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата сделки')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='munepit.building', verbose_name='Здание')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='munepit.player', verbose_name='Покупатель')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='munepit.resource', verbose_name='Ресурс')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='munepit.player', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-date_created'],
            },
        ),
    ]
