# Generated by Django 5.2.7 on 2026-02-22 17:50

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructedBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100, verbose_name='Название здания')),
                ('building_type', models.CharField(choices=[('factory', 'Фабрика'), ('business', 'Бизнес'), ('residential', 'Жилое'), ('other', 'Другое')], db_index=True, max_length=20, verbose_name='Тип здания')),
                ('owner_id', models.CharField(db_index=True, max_length=50, verbose_name='Номер игрока-владельца')),
                ('built_by', models.CharField(max_length=100, verbose_name='Построил (модератор)')),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата постройки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость постройки')),
                ('last_profit_collected', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее получение прибыли')),
                ('income_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход в минуту')),
            ],
            options={
                'verbose_name': 'Построенное здание',
                'verbose_name_plural': 'Построенные здания',
            },
        ),
        migrations.CreateModel(
            name='Convict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер игрока')),
                ('player_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО игрока')),
                ('crime_description', models.TextField(verbose_name='Описание преступления')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа')),
                ('confiscation', models.BooleanField(default=False, verbose_name='Конфискация имущества')),
                ('sentence_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Срок каторги (лет)')),
                ('sentenced_by', models.CharField(max_length=100, verbose_name='Приговорил')),
                ('sentenced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата приговора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Каторжник',
                'verbose_name_plural': 'Каторжники',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Игрок-должник')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма кредита')),
                ('term_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Срок (кол-во платежей)')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячный платеж')),
                ('remaining_payments', models.IntegerField(verbose_name='Осталось платежей')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего выплачено')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Выдал')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('last_payment_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний платеж')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='DynamicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(db_index=True, max_length=100, verbose_name='Товар')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('pmax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pmax')),
                ('n_for_drop', models.IntegerField(verbose_name='N для падения')),
                ('t_recovery', models.IntegerField(verbose_name='T восстановления (сек)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('sales_count', models.IntegerField(default=0, verbose_name='Продаж с последнего восстановления')),
            ],
            options={
                'verbose_name': 'Динамическая цена',
                'verbose_name_plural': 'Динамические цены',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('resource', 'Ресурс (Остров)'), ('building', 'Здание'), ('processing', 'Обработка'), ('goods', 'Товар (Великобритания)'), ('ship', 'Корабль'), ('gear', 'Шестерня'), ('fine', 'Штраф'), ('other', 'Прочее')], db_index=True, max_length=20, verbose_name='Категория')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена')),
                ('pmax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pmax (стартовая цена)')),
                ('n_for_drop', models.IntegerField(blank=True, null=True, verbose_name='N (кол-во для падения цены на 1)')),
                ('t_recovery', models.IntegerField(blank=True, null=True, verbose_name='T (секунд для восстановления)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='Privateer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер игрока')),
                ('ship_type', models.CharField(choices=[('frigate', 'Фрегат'), ('battleship', 'Линкор'), ('steam_frigate', 'Паровой фрегат')], max_length=20, verbose_name='Корабль')),
                ('last_payment_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний платеж')),
                ('complaints', models.IntegerField(default=0, verbose_name='Количество жалоб')),
                ('licensed_by', models.CharField(max_length=100, verbose_name='Лицензию выдал')),
                ('licensed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Капер',
                'verbose_name_plural': 'Каперы',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('table', models.CharField(choices=[('island', 'Остров'), ('britain', 'Великобритания')], max_length=20, verbose_name='Стол')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='building',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='resource',
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('author', models.CharField(max_length=100, verbose_name='Автор (модератор)')),
                ('table', models.CharField(choices=[('island', 'Остров'), ('britain', 'Великобритания')], db_index=True, max_length=20, verbose_name='Стол')),
                ('action_type', models.CharField(choices=[('deal', 'Сделка'), ('court', 'Суд'), ('release', 'Выход с каторги'), ('purchase', 'Покупка ресурса'), ('building', 'Постройка здания'), ('processing', 'Обработка ресурса'), ('profit', 'Получение прибыли'), ('demolition', 'Снос здания'), ('sale', 'Продажа товара'), ('ship_deal', 'Сделка с кораблем'), ('factory_work', 'Работа на заводе'), ('credit_issue', 'Выдача кредита'), ('credit_payment', 'Внесение платежа'), ('coal_purchase', 'Покупка угля'), ('privateer_license', 'Каперская лицензия'), ('privateer_ship', 'Смена корабля'), ('privateer_complaint', 'Жалоба'), ('privateer_payment', 'Платеж капера'), ('quest_accept', 'Принятие задания')], db_index=True, max_length=30, verbose_name='Тип действия')),
                ('player_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер игрока')),
                ('details', models.JSONField(default=dict, verbose_name='Детали операции')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Логи действий',
                'indexes': [models.Index(fields=['timestamp', 'action_type'], name='munepit_log_timesta_089b07_idx'), models.Index(fields=['player_id', 'timestamp'], name='munepit_log_player__510a43_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
