# Generated by Django 5.2.7 on 2026-03-07 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0002_constructedbuilding_convict_credit_dynamicprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convict',
            name='sentence_years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Срок каторги (лет)'),
        ),
    ]
