# Generated by Django 5.2.7 on 2026-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0003_alter_convict_sentence_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicprice',
            name='pmin',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Pmin (минимальная цена)'),
        ),
    ]
