# Generated by Django 5.2.7 on 2026-03-08 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0004_dynamicprice_pmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=50, verbose_name='Номер игрока (капер)')),
                ('description', models.TextField(help_text='Что нужно сделать', verbose_name='Описание задания')),
                ('reward', models.DecimalField(decimal_places=2, help_text='Сколько получит капер за выполнение', max_digits=10, verbose_name='Сумма награды')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Выдал (модератор)')),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, help_text='Задание еще не выполнено', verbose_name='Активно')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('completed_by', models.CharField(blank=True, max_length=100, verbose_name='Принял (капер)')),
                ('is_public', models.BooleanField(default=False, help_text='Если True - задание видят все каперы', verbose_name='Публичное задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['is_active', 'player_id'], name='munepit_que_is_acti_36b337_idx'), models.Index(fields=['is_active', 'is_public'], name='munepit_que_is_acti_98a0e0_idx')],
            },
        ),
    ]
