# Generated by Django 5.2.7 on 2026-03-09 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0005_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, max_length=50, verbose_name='Номер игрока')),
                ('ship_type', models.CharField(choices=[('basic', 'Люггер базовый'), ('armed', 'Люггер с орудиями')], max_length=20, verbose_name='Тип корабля')),
                ('bricks_count', models.IntegerField(default=10, verbose_name='Количество кирпичей')),
                ('exchanged_by', models.CharField(max_length=100, verbose_name='Выдал (модератор)')),
                ('exchanged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обмена')),
            ],
            options={
                'verbose_name': 'Обмен кирпичей',
                'verbose_name_plural': 'Обмены кирпичей',
            },
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='category',
            field=models.CharField(choices=[('resource', 'Ресурс (Остров)'), ('building', 'Здание'), ('processing', 'Обработка'), ('goods', 'Товар (Великобритания)'), ('ship', 'Корабль'), ('brick', 'Кирпичи'), ('fine', 'Штраф'), ('other', 'Прочее'), ('starter_ship', 'Стартовый корабль')], db_index=True, max_length=20, verbose_name='Категория'),
        ),
    ]
