# Generated by Django 5.2.7 on 2026-03-09 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0006_brickexchange_alter_pricelist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала игры')),
            ],
            options={
                'verbose_name': 'Настройки игры',
                'verbose_name_plural': 'Настройки игры',
            },
        ),
    ]
