# Generated by Django 5.2.7 on 2026-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0007_gamesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='pmin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pmin (минимальная цена)'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='category',
            field=models.CharField(choices=[('resource', 'Ресурс (Остров)'), ('building', 'Здание'), ('factory', 'Фабрика'), ('business', 'Бизнес'), ('processing', 'Обработка'), ('goods', 'Товар (Великобритания)'), ('ship', 'Корабль'), ('brick', 'Кирпичи'), ('starter_ship', 'Стартовый корабль'), ('fine', 'Штраф'), ('other', 'Прочее')], db_index=True, max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='pmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pmax (максимальная цена)'),
        ),
    ]
