# Generated by Django 5.2.7 on 2026-03-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0008_pricelist_pmin_alter_pricelist_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brickexchange',
            options={'ordering': ['-exchanged_at'], 'verbose_name': 'Обмен кирпичей', 'verbose_name_plural': 'Обмены кирпичей'},
        ),
    ]
