# Generated by Django 5.2.7 on 2026-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munepit', '0009_alter_brickexchange_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('category', models.CharField(default='product', max_length=50, verbose_name='Категория')),
                ('output_quantity', models.IntegerField(default=1, verbose_name='Количество на выходе')),
                ('production_time', models.IntegerField(default=10, verbose_name='Время производства (сек)')),
                ('ingredients', models.JSONField(default=dict, verbose_name='Ингредиенты')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
